## Setup

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

## Data Loading

In [ ]:
df = pd.read_csv("../Data/V-Dem-CD-v16.csv", low_memory=False)
df.head()

C:\Users\Kalami\AppData\Local\Temp\ipykernel_1908\440291475.py:1: DtypeWarning: Columns (7,364,365,366,399,415,804,836,837,924,1240,1257,1486,3094,3168,3169,3341,3342,3344,3345,3347,3350,3352) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Data/V-Dem-CD-v16.csv")

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,v2edtefire_sd,v2edtefire_osp,v2edtefire_osp_codelow,v2edtefire_osp_codehigh,v2edtefire_osp_sd,v2edtefire_ord,v2edtefire_ord_codelow,v2edtefire_ord_codehigh,v2edtefire_mean,v2edtefire_nr
0,Mexico,MEX,3,1789,1789-01-01,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mexico,MEX,3,1789,1789-10-17,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mexico,MEX,3,1789,1789-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mexico,MEX,3,1790,1790-01-01,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mexico,MEX,3,1790,1790-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
list(df.columns)[:30]

['country_name',
 'country_text_id',
 'country_id',
 'year',
 'historical_date',
 'project',
 'historical',
 'histname',
 'codingstart',
 'codingend',
 'codingstart_contemp',
 'codingend_contemp',
 'codingstart_hist',
 'codingend_hist',
 'gapstart1',
 'gapstart2',
 'gapstart3',
 'gapend1',
 'gapend2',
 'gapend3',
 'gap_index',
 'COWcode',
 'v2x_polyarchy',
 'v2x_polyarchy_codelow',
 'v2x_polyarchy_codehigh',
 'v2x_polyarchy_sd',
 'v2x_libdem',
 'v2x_libdem_codelow',
 'v2x_libdem_codehigh',
 'v2x_libdem_sd']

## Data Processing

In [9]:
# extract only the relevant columns
df_f = df[
    [
        "country_name",
        "country_text_id",
        "year",
        "historical_date",
        "codingstart",
        "codingend",
        "v2x_polyarchy",
        "v2x_libdem",
        "v2x_partipdem",
        "v2x_delibdem",
        "v2x_egaldem",
    ]
]

In [10]:
# extract only the relevant countries (Hungary in this case)
df_h = df_f[df_f["country_name"] == "Hungary"]

In [12]:
df_h.head()

,country_name,country_text_id,year,historical_date,codingstart,codingend,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2x_delibdem,v2x_egaldem
74381,Hungary,HUN,1789,1789-01-01,1789,2025,NaN,NaN,NaN,NaN,NaN
74382,Hungary,HUN,1789,1789-12-31,1789,2025,0.057,0.069,0.091,NaN,NaN
74383,Hungary,HUN,1790,1790-01-01,1789,2025,0.057,0.069,0.091,NaN,NaN
74384,Hungary,HUN,1790,1790-11-12,1789,2025,0.057,0.069,0.091,NaN,NaN
74385,Hungary,HUN,1790,1790-12-31,1789,2025,0.057,0.069,0.091,NaN,NaN

## Visualizations